In [ ]:
# Installation
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
print(arr)

[10 20 30 40 50]


In [ ]:
%%timeit
sum = 0
x = list(range(100000))
for i in x:
  sum = sum + i

In [ ]:
%%timeit
sum = 0
x_a = np.arange(100000)
for i in x_a:
  sum = sum + i

In [ ]:
arr.size

5

In [ ]:
arr.ndim

1

In [ ]:
arr.shape

(5,)

In [ ]:
len(arr)

5

## Two Dimensional Array

In [ ]:
arr_2d = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500]
])


In [ ]:
print(arr_2d)

[[ 10  20  30  40  50]
 [100 200 300 400 500]]


In [ ]:
# Check its size
arr_2d.size

10

In [ ]:
# Check its dimensionality
arr_2d.ndim

2

In [ ]:
# Check its shape
arr_2d.shape

(2, 5)

In [ ]:
len(arr_2d)

2

In [ ]:
type([[1,2,3,4],[5,6,7,8]])

list

In [ ]:
# Check the object's type
type(arr_2d)

numpy.ndarray

In [ ]:
# Check datatype of array elements
arr_2d.dtype

dtype('int64')

# Rules For Every NumPy Array
There are two basic rules for every numpy array..

Every element in the array must be of the same type and size.
If an array's elements are also arrays, those inner arrays must have the same type and number of elements as each other. In other words, multidimensional arrays must be rectangular, not jagged

In [ ]:
np.array([1, 2, 3])

In [ ]:
np.array([1, 'hello', 3])

array(['1', 'hello', '3'], dtype='<U21')

If you try to make an array from a list that contains a mix of integers and strings, numpy doesn't error. But, it casts the integers to strings in order to satisfy the property that every element is the same type.

In [ ]:
np.array([
    [1, 2, 3, 4],
    [5, 6]
])

<ipython-input-25-034e6ba25560>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([


array([list([1, 2, 3, 4]), list([5, 6])], dtype=object)

If you try to make an array from jagged lists like this, numpy doesn't error but it creates an array of objects. This means the array is essentially a Python list and lacks the performance benefits of using an array.

# Creating Numpy Arrays

In [ ]:
# Make 1D Array from a list
np.array(['a', 'b', 'c'])

array(['a', 'b', 'c'], dtype='<U1')

In [ ]:
# Make 2D Array from a list of lists
np.array([
    ['a', 'b'],
    ['c', 'd'],
    ['e', 'f']
])

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f']], dtype='<U1')

In [ ]:
# Make a 3D Array from a list of list of lists
np.array([
    [
        ['a', 'b'],
        ['c', 'd'],
        ['e', 'f']
    ],
    [
        ['g', 'h'],
        ['i', 'j'],
        ['k', 'l']
    ]
])

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']],

       [['g', 'h'],
        ['i', 'j'],
        ['k', 'l']]], dtype='<U1')

In [ ]:
# Make Array of Zeros
np.zeros(shape=3)

array([0., 0., 0.])

In [ ]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Make an array filled with any value
np.full(shape = (3,5), fill_value = 'PARUL')

array([['PARUL', 'PARUL', 'PARUL', 'PARUL', 'PARUL'],
       ['PARUL', 'PARUL', 'PARUL', 'PARUL', 'PARUL'],
       ['PARUL', 'PARUL', 'PARUL', 'PARUL', 'PARUL']], dtype='<U5')

In [ ]:
# How to make a sequence array 1, 2, ... N
np.arange(start=1, stop=15, step=4)

array([ 1,  5,  9, 13])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Indexing in Arrays

In [ ]:
foo = np.array([10, 20, 30, 40, 50])

In [ ]:
print(foo)

[10 20 30 40 50]


In [ ]:
# Accessing an element
print(foo[4])
print(foo[1])

50
20


In [ ]:
# Negative Indexing
print(foo[-1])
print(foo[-2])
print(foo[-3])

50
40
30


In [ ]:
# Out of bounds error
print(foo[999])

IndexError: ignored

In [ ]:
# Modifying an element
foo[1] = 99
print(foo)

[10 99 30 40 50]


In [ ]:
# Accessing Multiple Elements
print(foo[[3, 0, 4]])

[40 10 50]


In [ ]:
# Accessing Multiple Elements with same indices
print(foo[[0, 1, 0,1,1,3]])

[10 99 10 99 99 40]


In [ ]:
# Using elements of another numpy array as indices
print(foo[np.zeros(shape=3, dtype='int64')])

[10 10 10]


In [ ]:
# Modifying multiple elements at once
foo[[0, 1, 4]] = [100, 200, 400]

In [ ]:
# Assign everything to a scalar
foo[[0, 1, 4]] = 99

Array Slicing

foo[ start index : end index : step size ]

In [ ]:
# Get every element from index 2 inclusive to the end of the array
print(foo[2:])

In [ ]:
# Get every other element from the beginning of the array to the end
print(foo[::2])

# Transposing and Reshaping an Array

In [ ]:
arr = np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
x = arr.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
y = x.transpose()
y

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
y.T

array([[0, 1, 2],
       [3, 4, 5]])

## Stacking Arrays

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

# Array Operations

In [ ]:
data = np.array([76,82,4,90,213])

In [ ]:
data.min()

4

In [ ]:
data.max()

213

In [ ]:
data.argmin()

2

In [ ]:
data.argmax()

4

In [ ]:
data.sum()

465

# Basic Math Operations on Arrays

In [ ]:
foo = np.array([[4,3], [1,0]])
bar = np.array([[1,2], [3,4]])

In [ ]:
print(foo)
print(bar)

[[4 3]
 [1 0]]
[[1 2]
 [3 4]]


In [ ]:
# Addition
foo + bar

array([[5, 5],
       [4, 4]])

The values of foo and bar get added element-wise. This pattern of element-wise addition holds true for every math operation between identically sized arrays.

In [ ]:
# Subtraction
foo - bar

array([[ 3,  1],
       [-2, -4]])

In [ ]:
# Multiplication
foo * bar

array([[4, 6],
       [3, 0]])

In [ ]:
# Division
foo / bar

array([[4.        , 1.5       ],
       [0.33333333, 0.        ]])

In [ ]:
# Matrix Multiplication
foo @ bar

array([[13, 20],
       [ 1,  2]])

## Broadcasting



The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.

![x](https://miro.medium.com/v2/resize:fit:1400/1*lY8Ve6Uz_bqVI5NPh5RPZA.png)



In [ ]:
foo + 5

In [ ]:
a1 = np.arange(8).reshape(2,4)
a2  = np.arange(8,16).reshape(2,4)

In [ ]:
print(a1)
print(a2)

In [ ]:
a1 + a2

In [ ]:
a3= np.arange(3).reshape(1,3)
a4 = np.arange(9).reshape(3,3)

In [ ]:
print(a3)
print(a4)

In [ ]:
a3  + a4

# Getting Unique Values

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [ ]:
np.unique(a, return_counts=True) # collections.Counter()

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [ ]:
# 2D Array
a_2d = np.array([[1, 1, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
np.unique(a_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# For rows
np.unique(a_2d, axis=0)

array([[ 1,  1,  3,  4],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# For columns
np.unique(a_2d, axis=1)

array([[ 1,  1,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

# Reverse An Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
# Reverse only rows
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [ ]:
# Reverse only columns
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

# Flattening an Array

When you use flatten, changes to your new array won’t change the parent array.

But when you use ravel, the changes you make to the new array will affect the parent array.

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


# Saving Arrays to Disk

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
np.save('filename', a)

In [ ]:
b = np.load('filename.npy')
print(b)

[1 2 3 4 5 6]
